# This file is required for deploying on fly.io.

# Replace "eido-agent" with your actual app name
app = "eido-agent"
primary_region = "lax"

# NEW SECTION: Define the machine size to prevent Out Of Memory errors.
# The 'shared-cpu-1x' with 512MB of memory should be sufficient for the ML models.
[machines]
  size = "shared-cpu-1x"
  memory_mb = 1_024

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0 # Use 1 for an always-on free tier machine
  # This tells Fly to run the default CMD from the Dockerfile in a process named 'app'.
  # Our entrypoint will receive "api" as the command.
  processes = ["app"]

  [[http_service.checks]]
    type = "http"
    interval = "15s"
    timeout = "10s"
    # Increased grace period to give the app time to load ML models before first check.
    grace_period = "45s"
    method = "GET"
    path = "/"
    protocol = "http"